[package]
name = "guners"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.1"
dasp_sample = "0.11.0"
rustfft = "6.1.0"
